### ISSUE TITLE
XMR view key

### ISSUE THREAD

**Issue by benkaiser** [bitrequest/webshop-integration#1]
I've got the dialog launching for most currencies, however the XMR (Monero) one is showing a notification that it is not monitored.

I have the view key available, how do I pass it in to receive monitoring for the monero transactions? Can this be added to the README here?

Thanks!

**Comment by bitrequest** [comment]
Added: https://github.com/bitrequest/bitrequest.github.io/commit/4f7f777e909074e949bb4c32c8e1226ba62d79e8
Implemetation: https://www.bitrequest.io/request-url/
