### ISSUE TITLE
Leaving Payment Open Requests to Close

### ISSUE THREAD

**Issue by benkaiser** [bitrequest/webshop-integration#2]
![image](https://user-images.githubusercontent.com/608054/128508883-d3d9b111-742f-450a-9867-782c67327bd5.png)

If I just leave the webshop window open, I get the request to close / re-start the transaction every couple of minutes (not entirely sure of the interval, might be 10 minutes)

**Comment by bitrequest** [comment]
That's by design. If you leave it untouched it will close after 3 minutes.

**Comment by benkaiser** [comment]
Even for Bitcoin? (i.e. networks where the transaction might take 10-20 minutes)?

**Comment by bitrequest** [comment]
The transaction should appear almost immediately on a blockexplorer (mempool) even if it's unconfirmed.

**Comment by benkaiser** [comment]
Ah good point.
