### ISSUE TITLE
Button to close on success?

### ISSUE THREAD

**Issue by benkaiser** [bitrequest/webshop-integration#3]
When a payment is completed, although the data is posted back to the checkout, the iframe isn't closed. Is there an API I can call from the hosting frame to close the payment window?

![image](https://user-images.githubusercontent.com/608054/128511269-be6070f0-c354-4a75-9149-b8b43ccda694.png)

**Comment by bitrequest** [comment]
Yep, you can use closeframe()
(in your result_callback() function)

**Comment by benkaiser** [comment]
Perfect!
